In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
phase5_results = pd.read_csv("forecast_results.csv")

phase5_results

,Sequence,Horizon,Model,MAE,MSE,RMSE,MAPE,R2,Bias
0,24,24,RNN,1685.860767,5.500636e+06,2345.343485,5.462425,0.869330,238.756741
1,24,24,LSTM,1512.914477,4.690809e+06,2165.827633,4.896483,0.888568,324.474172
2,24,24,GRU,1488.760950,4.550923e+06,2133.289171,4.805769,0.891891,246.618093
3,24,24,Bi-LSTM,1523.322924,4.654856e+06,2157.511483,4.937271,0.889422,149.586331
4,48,24,RNN,1566.645508,4.637170e+06,2153.408885,5.001122,0.889842,60.842667
5,48,24,LSTM,1417.016894,4.063550e+06,2015.824985,4.559036,0.903469,307.211975
6,48,24,GRU,1407.372058,3.985015e+06,1996.250119,4.497683,0.905334,91.033141
7,48,24,Bi-LSTM,1414.019266,4.042415e+06,2010.575733,4.513480,0.903971,112.758116
8,168,24,RNN,1894.869473,6.283783e+06,2506.747479,6.203033,0.850726,388.770340
9,168,24,LSTM,1356.110610,3.728263e+06,1930.871173,4.324987,0.911434,267.204871
10,168,24,GRU,1364.036036,3.715291e+06,1927.508982,4.343224,0.911742,331.006106
11,168,24,Bi-LSTM,1340.928649,3.734168e+06,1932.399664,4.254994,0.911293,247.408706

In [5]:
best_phase5 = phase5_results.loc[
    phase5_results["RMSE"].idxmin()
]

best_phase5

Sequence               168
Horizon                 24
Model                  GRU
MAE            1364.036036
MSE         3715290.876289
RMSE           1927.508982
MAPE              4.343224
R2                0.911742
Bias            331.006106
Name: 10, dtype: object

In [8]:
# phase _06 model improvement

phase6_results = pd.read_csv("phase6_model_improvement_results.csv")

phase6_results

,Experiment,MAE,MSE,RMSE,MAPE,R2,Bias,Batch Size
0,Phase 5 Baseline GRU,1364.036036,3.715291e+06,1927.508982,4.343224,0.911742,331.006106,NaN
1,GRU + Lag + Rolling Features,1344.752508,3.577181e+06,1891.343700,4.282023,0.915016,218.576061,NaN
2,GRU + Lag + Rolling + Dropout,1364.962779,3.659960e+06,1913.102271,4.344613,0.913049,222.825781,NaN
3,GRU + Lag + Rolling + BatchNorm,4283.947497,2.859154e+07,5347.105982,14.103207,0.320741,-295.481652,NaN
4,GRU + Features + BatchNorm + RMSprop,2040.924826,7.333190e+06,2707.986425,6.510526,0.825783,-657.753587,NaN
5,GRU + Features + BatchNorm + LR Scheduler,1692.209192,5.052011e+06,2247.667989,5.549312,0.879978,941.814409,NaN
6,NaN,2893.749202,1.281856e+07,3580.302135,9.508573,0.695465,-277.001614,64.0
7,Best Batch Size (64),2893.749202,1.281856e+07,3580.302135,9.508573,0.695465,-277.001614,NaN
8,GRU + Features + BatchNorm + LR Scheduler,1692.209192,5.052011e+06,2247.667989,5.549312,0.879978,941.814409,NaN
9,Architecture (GRU_128),1569.701450,4.482433e+06,2117.175813,5.002250,0.893509,-147.454441,NaN
10,GRU Hyperparameter Tuning,1592.599503,4.657884e+06,2158.213157,5.205846,0.889341,513.710997,NaN

In [10]:
phase6_best = phase6_results.loc[
    phase6_results["MAE"].idxmin()
]

phase6_best

Experiment    GRU + Lag + Rolling Features
MAE                            1344.752508
MSE                         3577180.991042
RMSE                             1891.3437
MAPE                              4.282023
R2                                0.915016
Bias                            218.576061
Batch Size                             NaN
Name: 1, dtype: object

In [11]:
#Phase_08
phase6_results = pd.read_csv("phase7_validation_comparison.csv")

phase6_results

  Metric        30-Day        60-Day
0    MAE  1.554617e+03  1.784824e+03
1    MSE  4.070095e+06  5.525614e+06
2   RMSE  2.017448e+03  2.350663e+03
3   MAPE  5.418525e+00  5.494065e+00
4     R2  6.881053e-01  8.254610e-01
5   Bias  5.630314e+02  3.477451e+02

In [13]:
best_model = phase5_results.loc[
    phase5_results["RMSE"].idxmin()
]

print("BEST PHASE 5 MODEL")
print("------------------")

print("Model:", best_model["Model"])
print("Sequence:", best_model["Sequence"])
print("Horizon:", best_model["Horizon"])
print("MAE:", best_model["MAE"])
print("RMSE:", best_model["RMSE"])
print("MAPE:", best_model["MAPE"])
print("R2:", best_model["R2"])
print("Bias:", best_model["Bias"])

BEST PHASE 5 MODEL
------------------
Model: GRU
Sequence: 168
Horizon: 24
MAE: 1364.0360357036266
RMSE: 1927.5089821552735
MAPE: 4.34322444504244
R2: 0.9117418842316476
Bias: 331.0061059075935