In [1]:
import sys
import subprocess

subprocess.run([sys.executable, "-m", "pip", "--version"])

CompletedProcess(args=['C:\\Users\\Suthishna kumar\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--version'], returncode=0)

In [2]:
import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip",
    "install", "--force-reinstall", "numpy==1.26.4"
])

0

In [3]:
import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip",
    "install", "--force-reinstall",
    "sentence-transformers==5.1.2",
    "transformers==4.57.6",
    "tokenizers==0.22.2",
    "huggingface-hub==0.36.2",
    "safetensors==0.7.0",
    "faiss-cpu==1.13.0"
])

0

In [5]:
import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip",
    "uninstall", "-y", "torchvision"
])

subprocess.check_call([
    sys.executable, "-m", "pip",
    "install", "torchvision==0.17.2"
])

0

In [5]:
import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip",
    "install", "--force-reinstall", "numpy==1.26.4"
])

0

In [3]:
import sys
import subprocessUM 

result = subprocess.run(
    [sys.executable, "-m", "pip", "install", "tf-keras"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Collecting tf-keras
  Using cached tf_keras-2.20.1-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow<2.21,>=2.20 (from tf-keras)
  Using cached tensorflow-2.20.0-cp39-cp39-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.2.2)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.4.0)
Requirement already satisfied: packaging in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (26.3)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (6.33.6)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.32.5)
Requirement already satisfied: setuptools in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (82.0.1)
Requirement already satisfied: six>=1.12.0 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.71.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.10.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.13.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (2026.7.22)
Requirement already satisfied: markdown>=2.6.8 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.8)
Requirement already satisfied: pillow in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from astunparse>=1.6.0->tensorflow<2.21,>=2.20->tf-keras) (0.47.0)
Requirement already satisfied: rich in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (14.0.0)
Requirement already satisfied: namex in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.0.9)
Requirement already satisfied: optree in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.15.0)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from markdown>=2.6.8->tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (8.7.0)
Requirement already satisfied: zipp>=3.20 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.21.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\suthishna kumar\appdata\roaming\python\python39\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.1.2)
Using cached tf_keras-2.20.1-py3-none-any.whl (1.7 MB)
Using cached tensorflow-2.20.0-cp39-cp39-win_amd64.whl (331.7 MB)
Installing collected packages: tensorflow, tf-keras

  Attempting uninstall: tensorflow

    Found existing installation: tensorflow 2.16.1

    Uninstalling tensorflow-2.16.1:

      Successfully uninstalled tensorflow-2.16.1

   ---------------------------------------- 0/2 [tensorflow]
   ---------------------------------------- 0/2 [tensorflow]
   ---------------------------------------- 0/2 [tensorflow]
   ---------------------------------------- 0/2 [tensorflow]
  Rolling back uninstall of tensorflow
   ---------------------------------------- 0/2 [tensorflow]
  Moving to c:\users\suthishna kumar\appdata\local\programs\python\python39\lib\site-packages\tensorflow-2.16.1.dist-info\
   from C:\Users\Suthishna kumar\AppData\Local\Programs\Python\Python39\Lib\site-packages\~ensorflow-2.16.1.dist-info
   ---------------------------------------- 0/2 [tensorflow]
   ---------------------------------------- 0/2 [tensorflow]


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Suthishna kumar\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\tensorflow\\compiler\\mlir\\quantization\\tensorflow\\python\\pywrap_function_lib.pyd'
Consider using the `--user` option or check the permissions.

In [1]:
import os
os.environ["USE_TF"] = "0"
os.environ["USE_TORCH"] = "1"

from sentence_transformers import SentenceTransformer
import faiss

print("Imports successful")

C:\Users\Suthishna kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Imports successful

In [2]:
import pandas as pd
import numpy as np
import os
import time
import pickle

from sentence_transformers import SentenceTransformer
import faiss

In [3]:
from sentence_transformers import SentenceTransformer
import faiss

In [4]:
tickets = pd.read_csv(
    "processed/processed_support_tickets.csv"
)

print("Shape:", tickets.shape)

tickets[
    ["Ticket ID", "Ticket Type", "Ticket Subject", "CleanText"]
].head()

Shape: (8469, 20)

,Ticket ID,Ticket Type,Ticket Subject,CleanText
0,1,Technical issue,Product setup,product setup issue productpurchased please as...
1,2,Technical issue,Peripheral compatibility,peripheral compatibility issue productpurchase...
2,3,Technical issue,Network problem,network problem facing problem productpurchase...
3,4,Billing inquiry,Account access,account access issue productpurchased please a...
4,5,Billing inquiry,Data loss,data loss issue productpurchased please assist...

In [5]:
tickets["SearchText"] = (
    tickets["Ticket Subject"].fillna("").astype(str)
    + ". "
    + tickets["CleanText"].fillna("").astype(str)
)

tickets["SearchText"].head()

0    Product setup. product setup issue productpurc...
1    Peripheral compatibility. peripheral compatibi...
2    Network problem. network problem facing proble...
3    Account access. account access issue productpu...
4    Data loss. data loss issue productpurchased pl...
Name: SearchText, dtype: object

In [6]:
model_name = "all-MiniLM-L6-v2"

embedding_model = SentenceTransformer(
    model_name
)

print("Embedding model loaded.")

C:\Users\Suthishna kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Suthishna kumar\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

Embedding model loaded.

In [7]:
start_time = time.time()

embeddings = embedding_model.encode(
    tickets["SearchText"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

embedding_time = time.time() - start_time

print("Embedding shape:", embeddings.shape)
print(f"Embedding time: {embedding_time:.2f} seconds")

Batches: 100%|██████████| 265/265 [01:39<00:00,  2.65it/s]

Embedding shape: (8469, 384)
Embedding time: 100.14 seconds

In [8]:
faiss.normalize_L2(embeddings)

print("Embeddings normalized.")

Embeddings normalized.

In [9]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(
    dimension
)

index.add(
    embeddings
)

print("FAISS index created.")
print("Number of vectors:", index.ntotal)

FAISS index created.
Number of vectors: 8469

In [11]:
query = "My product is not working properly"

query_embedding = embedding_model.encode(
    [query],
    convert_to_numpy=True
)

faiss.normalize_L2(query_embedding)

In [12]:
distances, indices = index.search(
    query_embedding,
    5
)

In [13]:
results = tickets.iloc[
    indices[0]
][[
    "Ticket ID",
    "Ticket Type",
    "Ticket Subject",
    "Ticket Description"
]].copy()

results["Similarity"] = distances[0]

results

,Ticket ID,Ticket Type,Ticket Subject,Ticket Description,Similarity
7711,7712,Product inquiry,Display issue,I'm having an issue with the {product_purchase...,0.603950
4693,4694,Cancellation request,Display issue,I'm facing a problem with my {product_purchase...,0.595045
4410,4411,Technical issue,Product setup,I'm facing a problem with my {product_purchase...,0.581866
4629,4630,Refund request,Display issue,I'm having an issue with the {product_purchase...,0.580553
321,322,Billing inquiry,Product setup,I'm facing a problem with my {product_purchase...,0.579668

In [14]:
def semantic_search(query, top_k=5):

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True
    )

    faiss.normalize_L2(query_embedding)

    distances, indices = index.search(
        query_embedding,
        top_k
    )

    results = tickets.iloc[
        indices[0]
    ].copy()

    results["Similarity"] = distances[0]

    return results

In [15]:
semantic_search(
    "I have a problem with my bill",
    top_k=5
)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating,Text,CleanText,WordCount,SearchText,Similarity
724,725,Danielle Gordon,yfrank@example.org,60,Female,Asus ROG,2021-02-25,Technical issue,Payment issue,I'm having an issue with the {product_purchase...,...,Low,Phone,NaN,NaN,NaN,Payment issue I'm having an issue with the {pr...,payment issue issue productpurchased please as...,25,Payment issue. payment issue issue productpurc...,0.509524
3220,3221,Valerie Cooper,whernandez@example.org,34,Female,Nintendo Switch Pro Controller,2020-01-08,Product inquiry,Payment issue,I'm having an issue with the {product_purchase...,...,Medium,Social media,NaN,NaN,NaN,Payment issue I'm having an issue with the {pr...,payment issue issue productpurchased please as...,25,Payment issue. payment issue issue productpurc...,0.484266
7164,7165,Troy Mann,kelly14@example.com,42,Male,Roomba Robot Vacuum,2021-09-02,Refund request,Account access,I'm having an issue with the {product_purchase...,...,High,Email,NaN,NaN,NaN,Account access I'm having an issue with the {p...,account access issue productpurchased please a...,21,Account access. account access issue productpu...,0.483987
2035,2036,Allison Sullivan,davidford@example.net,61,Male,Canon DSLR Camera,2021-04-17,Cancellation request,Payment issue,I'm having an issue with the {product_purchase...,...,Medium,Email,2023-06-01 17:38:30,2023-06-01 21:19:30,3.0,Payment issue I'm having an issue with the {pr...,payment issue issue productpurchased please as...,25,Payment issue. payment issue issue productpurc...,0.483549
707,708,Erika Wilkins,sara25@example.org,58,Male,Nest Thermostat,2021-10-28,Cancellation request,Payment issue,I'm having an issue with the {product_purchase...,...,Critical,Email,2023-06-01 01:16:54,2023-06-01 00:04:54,5.0,Payment issue I'm having an issue with the {pr...,payment issue issue productpurchased please as...,25,Payment issue. payment issue issue productpurc...,0.483094

In [16]:
semantic_search(
    "I cannot access my account",
    top_k=5
)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating,Text,CleanText,WordCount,SearchText,Similarity
6682,6683,Brittany Ortega,holmesjoseph@example.net,43,Other,Nikon D,2020-01-12,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,...,High,Social media,2023-06-01 22:31:01,2023-06-01 21:37:01,1.0,Account access I'm having an issue with the {p...,account access issue productpurchased please a...,27,Account access. account access issue productpu...,0.708757
7251,7252,David Johnson,amber32@example.org,36,Male,Autodesk AutoCAD,2020-01-10,Cancellation request,Account access,I'm having an issue with the {product_purchase...,...,Critical,Email,2023-06-01 09:54:02,NaN,NaN,Account access I'm having an issue with the {p...,account access issue productpurchased please a...,24,Account access. account access issue productpu...,0.703013
6767,6768,Joseph Leonard,danielreed@example.com,21,Other,GoPro Action Camera,2020-12-05,Refund request,Account access,I'm having an issue with the {product_purchase...,...,High,Email,NaN,NaN,NaN,Account access I'm having an issue with the {p...,account access issue productpurchased please a...,29,Account access. account access issue productpu...,0.702164
7459,7460,Justin Johnson,xmartinez@example.net,51,Female,Bose SoundLink Speaker,2021-11-28,Product inquiry,Account access,I'm having an issue with the {product_purchase...,...,Critical,Social media,2023-06-01 15:08:01,NaN,NaN,Account access I'm having an issue with the {p...,account access issue productpurchased please a...,24,Account access. account access issue productpu...,0.694011
1604,1605,Taylor Montoya,maryyork@example.org,22,Female,Dell XPS,2021-06-21,Billing inquiry,Account access,I've forgotten my password for my {product_pur...,...,Medium,Chat,2023-06-01 12:24:23,NaN,NaN,Account access I've forgotten my password for ...,account access ive forgotten password productp...,30,Account access. account access ive forgotten p...,0.691209

In [17]:
semantic_search(
    "My computer has a technical problem",
    top_k=5
)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating,Text,CleanText,WordCount,SearchText,Similarity
269,270,Kathleen Graves,coreymcmillan@example.net,64,Other,MacBook Pro,2021-05-10,Refund request,Hardware issue,I'm having an issue with the {product_purchase...,...,High,Social media,2023-06-01 07:21:57,2023-06-01 16:09:57,3.0,Hardware issue I'm having an issue with the {p...,hardware issue issue productpurchased please a...,31,Hardware issue. hardware issue issue productpu...,0.542506
2793,2794,Adriana Mason,jamesspencer@example.com,41,Other,LG Washing Machine,2020-02-05,Product inquiry,Hardware issue,I'm having an issue with the {product_purchase...,...,Low,Chat,NaN,NaN,NaN,Hardware issue I'm having an issue with the {p...,hardware issue issue productpurchased please a...,34,Hardware issue. hardware issue issue productpu...,0.512885
8345,8346,Alexis Bell,barbaragray@example.com,18,Other,Roomba Robot Vacuum,2021-12-29,Billing inquiry,Hardware issue,I'm having an issue with the {product_purchase...,...,Low,Social media,2023-06-01 14:37:41,2023-06-01 19:24:41,3.0,Hardware issue I'm having an issue with the {p...,hardware issue issue productpurchased please a...,28,Hardware issue. hardware issue issue productpu...,0.512315
1436,1437,Kelli Terrell,rfowler@example.net,27,Female,LG OLED,2020-04-21,Billing inquiry,Hardware issue,I'm having an issue with the {product_purchase...,...,Low,Social media,2023-06-01 06:02:36,NaN,NaN,Hardware issue I'm having an issue with the {p...,hardware issue issue productpurchased please a...,18,Hardware issue. hardware issue issue productpu...,0.504921
3653,3654,Sharon Kirk,ocampbell@example.org,68,Male,Xbox,2021-07-30,Technical issue,Hardware issue,I'm having an issue with the {product_purchase...,...,Low,Phone,NaN,NaN,NaN,Hardware issue I'm having an issue with the {p...,hardware issue issue productpurchased please a...,24,Hardware issue. hardware issue issue productpu...,0.504589

In [18]:
os.makedirs(
    "../vector_store",
    exist_ok=True
)

In [19]:
faiss.write_index(
    index,
    "../vector_store/ticket_faiss.index"
)

print("FAISS index saved.")

FAISS index saved.

In [20]:
with open(
    "../vector_store/embedding_model.txt",
    "w"
) as f:
    f.write(model_name)

print("Embedding model information saved.")

Embedding model information saved.

In [21]:
metadata = tickets[
    [
        "Ticket ID",
        "Ticket Type",
        "Ticket Subject",
        "Ticket Description",
        "SearchText"
    ]
].copy()

metadata.to_pickle(
    "../vector_store/ticket_metadata.pkl"
)

print("Ticket metadata saved.")

Ticket metadata saved.

In [22]:
loaded_index = faiss.read_index(
    "../vector_store/ticket_faiss.index"
)

loaded_metadata = pd.read_pickle(
    "../vector_store/ticket_metadata.pkl"
)

print("Vectors:", loaded_index.ntotal)
print("Metadata rows:", len(loaded_metadata))

Vectors: 8469
Metadata rows: 8469

In [23]:
query = "I cannot log into my account"

start = time.time()

query_embedding = embedding_model.encode(
    [query],
    convert_to_numpy=True
)

faiss.normalize_L2(query_embedding)

distances, indices = index.search(
    query_embedding,
    5
)

search_time = time.time() - start

print(
    f"Embedding + FAISS search time: "
    f"{search_time:.4f} seconds"
)

Embedding + FAISS search time: 0.0407 seconds